name: Cosmocc (x86_64-linux)

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Cosmocc-${{ matrix.arch }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Prepare local xmake
        run: cp -rf . ../xmake-source

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: local#../xmake-source

      - uses: bjia56/setup-cosmocc@main
        with:
          version: "3.9.7"

      - name: Build
        run: |
          cd core
          xmake f -p linux --cosmocc=y --embed=y -y -cvD
          xmake -v
          cd ..

      - name: Tests
        run: |
          ls -l core/build/
          core/build/xmake --version
          core/build/xmake lua -v -D tests/run.lua

      - uses: actions/upload-artifact@v4
        with:
          name: xmake-linux-x86_64
          path: core/build/xmake
